version: "3.4"

services:
  
  zokrates:

    container_name: "zokrates"
    environment: 
      RUST_MIN_STACK: 1000000
    image: "alvaround/zokrates-api:0.1.0"
    volumes:
      - ./prover-node/out:/app/out
    ports:
      - 8000:8000
 