apiVersion: v1
kind: Service
metadata:
  namespace: st-alonso
  name: zokrates-service
  labels:
    app: zokrates-api
spec:
  type: NodePort
  ports:
  - port: 8000
    protocol: TCP
    targetPort: 8000
    nodePort: 30123
  selector:
    app: zokrates-api 
status:
  loadBalancer: {}