apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: test-pod
  name: test-pod
  namespace: st-alonso
spec:
  containers:
  - image: alvaround/zokrates-api-tests:latest
    name: test-pod
    command: [ "python" ]
    args: [ 
      "run_test.py", 
      "trial_one_signature", 
      "trial_five_signatures", 
      "trial_ten_signatures",
    ]
    env:
    - name: CLUSTER_ADDRESS
      value: http://zokrates-service:8000
    volumeMounts:
    - name: zfs
      mountPath: /usr/app/results
    startupProbe:
      exec:
        command:
        - curl
        - ($CLUSTER_ADDRESS)/health
      failureThreshold: 30
      periodSeconds: 10
  volumes:
    - name: zfs
      persistentVolumeClaim:
        claimName: test-results-zfs-pvc
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
