#!/bin/sh

set -eu

cd prover-node

echo "***** Prover Node *****"
if ! cargo fmt -- --check
then
    cargo fmt --all
    echo "There were some code style issues."
    echo "Commit the changes done cargo fmt first."
    exit 1
fi

echo "No formating errors found"

if ! cargo clippy -p prover_node -- -D warnings
then
    cargo clippy -p prover_node --fix --allow-dirty
    echo "There were some clippy issues."
    echo "Commit the changes done cargo clippy first."
    exit 1
fi

echo "No clippy errors found"
echo "***********************"

# if ! cargo test
# then
#    echo "There are some test issues."
#    exit 1
# fi

exit 0
