on: [pull_request]

env:
  CARGO_TERM_COLOR: always

name: Prover

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      # `rustup` will need `curl` or `wget` later
      - run: sudo apt-get update && sudo apt-get install -y curl
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
          override: true
          components: rustfmt, clippy

  lint:
    needs: setup
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: prover-node
    steps:
      - uses: actions/checkout@v2
      - name: format check
        uses: actions-rs/cargo@v1
        with:
          command: fmt 
          args: --all --manifest-path prover-node/Cargo.toml -- --check
      # FIXME: skip clippy step as --no-deps option is not working on github acitons
      # - name: clippy
      #   uses: actions-rs/cargo@v1
      #   with:
      #     command: clippy 
      #     args: --no-deps --manifest-path prover-node/Cargo.toml -- -D warnings

  test:
    needs: lint
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: prover-node
    steps:
      - uses: actions/checkout@v2
      - name: run unit-test
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --manifest-path prover-node/Cargo.toml