on: [pull_request]

env:
  CARGO_TERM_COLOR: always

name: Prover

jobs:

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
          override: true
          components: rustfmt, clippy
      - name: linting check
        run: |
          cd prover-node
          cargo fmt --all -- --check
          cargo clippy -- -D warnings

  test:
    needs: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
          override: true
      - name: run unit-test
        run: |
          cd prover-node
          cargo test