on: [push, pull_request]

name: Prover

jobs:
  setup:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./prover-node
    steps:
      # `rustup` will need `curl` or `wget` later
      - run: apt-get update && apt-get install -y curl
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
          override: true
          components: rustfmt, clippy

  lint:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions-rs/cargo@v1
        with:
          run: fmt --all -- --check
      - uses: actions-rs/cargo@v1
        with:
          run: clippy -- -D warnings

  test:
    needs: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions-rs/cargo@v1
        with:
          run: test
